### ISSUE TITLE
Considerations on Themosis Plugin

### ISSUE THREAD

**Issue by thiagof** [themosis/plugin#1]
What should one consider when creating a themosis plugin?
I would like to be theme independent, but keep all the logic and functionality inside plugins.

Thank you

**Comment by jlambe** [comment]
Hi, 
currently the plugin boilerplate is empty as it is not yet developed. As of release 1.1.3, you can create a plugin like any WordPress plugins but in order to use the framework classes, you need to wrap your code after the `themosis_bootstrap` action hook.

Note that this is going to change with the 1.2.0 release. I haven't set it up yet but I know your request (like many others ask) is on top of the list for next release. 1.2.0 is changing the theme structure so I can mirror code for custom plugins. At release 1.2.0, the hook to listen to will be `themosis_bootstrap_plugins` but a complete plugin structure and documentation will only arrive on 1.3.0.

You'll be able to also write your own packages in place of plugins and autoload them with your project, if you're interested into this, check this repository for example: https://github.com/ithinkdancan/framework

**Comment by thiagof** [comment]
Hello, sounds good!

But can the plugin currently live without a themosis-framework `theme`?
Seems like the plugin can leverage themosis like the theme, could you confirm?

Yes all the work around composer packages is really useful!

**Comment by thiagof** [comment]
Yes I could easily decouple the theme bootstrap into a plugin. Thanks for the help.

I'm observing the framework is designed to serve a single instance, like the theme only.
When thinking plugins, we can have many plugins sharing or using the same framework.

Is this kind of feature planned for future releases, themosis to serve multiple plugins side-by-side?

**Comment by jlambe** [comment]
1. Yes you can build your own theme, the framework doesn't need the theme in order to work. Currently the plugin can indeed leverage themosis like the theme. Specify your plugin assets, views paths during bootstrap and you should be good to go.
2. The issue with multiple plugins is to handle name conflicts. You'll be able to do the same but we need to avoid conflicts with plugin classes (controllers, models, custom ones). So for plugin development, WordPress developers will have to start to use namespaces so you could run multiple plugins that share the framework classes.

So yes, this is planned ;)

**Comment by thiagof** [comment]
Cool.

The issues I see for the plugin development and multiple themosis components, on the current version, is on `themosis_bootstrap` and `setApplicationPaths` where it is configured a single instance application within themosis setup.

**Comment by jlambe** [comment]
Yes I'm aware of this but note that a lot of these issues are already fixed on master branch and for release 1.2.0. It will easier once release 1.2.0 is out in order to prepare for plugin development and custom packages.
