### ISSUE TITLE
Return a binary response

### ISSUE THREAD

**Issue by mickaelperrin** [themosis/plugin#10]
Hi,

I alm currently writing a plugin which generate a PDF file. I want to return the binary response with force download headers.

I was used to do in Symfony / Drupal something like :

        $response = new BinaryFileResponse($pdfFilePath);
        $response->setContentDisposition(ResponseHeaderBag::DISPOSITION_ATTACHMENT);
        return $response;

I have seen in the core of the framework, that themosis only return content and not headers as headers are managed by WP.

> // We only send back the content because, headers are already defined
> // by WordPress internals.

Could you tell me what's the themosis way of struggling with headers in this use case ?

Thanks,

**Comment by jlambe** [comment]
Yes, you need to write goo ol' header statements. Note that I haven't tested the `BinaryFileResponse` object. Perhaps you can still use some of its class methods to achieve the same result...

Otherwise for one project, we had to write those headers calls for PDF download from a controller method:

```php
$file_name = basename($file_path);

header('Content-Type: application/pdf');
header('Content-Disposition: attachment; filename="'.$file_name.'"');
header('Content-Transfer-Encoding: binary');
header('Content-Length: '.filesize(mb_convert_encoding($file_path, 'UTF-8')));
readfile(mb_convert_encoding($file_path, 'UTF-8'));
```

It can be called from your controller's method before returning a view or depending on your needs, we have called this from a `template_redirect` hook action as we needed to do some data check/parsing before downloading the PDF file.

Hope this helps.

**Comment by mickaelperrin** [comment]
Well not really what I was expecting for :)

But does the job quite well, thanks a lot !

**Comment by jlambe** [comment]
@mickaelperrin Perhaps there are enhancements in order to handle those scenarios. Some research need to be done so we can override the headers management from a response object.

We would also prefer to do it in a cleaner way so perhaps it will come as WordPress and the framework evolved.
